package site.asm0dey.poetdsl

import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.STRING
import site.asm0dey.poetdsl.ParamKind.VAL
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/** E2b items 2 and 3: KDoc on every declaration, and the file comment. */
class DocumentationTest {
    /**
     * The one that matters. `addKdoc` and `addFileComment` are **format** functions: a literal `%`
     * in the caller's prose either throws or silently consumes the next argument, and a generator
     * writing "100% covered" or documenting a `%s` placeholder has no idea it is holding a format
     * string. Every route into either of them therefore goes through `"%L"`, and this is what says
     * so — measured against KotlinPoet 2.3.0, where `addKdoc(text)` with this text raises
     * `IllegalArgumentException: index 1 for '% ' not in range (received 0 arguments)`.
     */
    @Test
    fun `a percent sign in documentation survives verbatim`() {
        val text = "100% done. A %L is a literal, %T a type, %S a string, and %% is an escape."
        val rendered = file("com.example", "A", fileComment = text) {
            `class`("C", kdoc = text) {
                `val`("p", INT, init = 1.lit, kdoc = text)
                `fun`(
                    "f",
                    param("x", INT, kdoc = text),
                    returns = INT,
                    receiver = STRING,
                    kdoc = text,
                    receiverKdoc = text,
                    returnsKdoc = text,
                ) { _ -> ret(1.lit) }
            }
        }.toString()
        // Seven occurrences — one for every route a caller's string has into KotlinPoet's
        // documentation API, and all seven of them: the file comment, the class, the property, the
        // function, its parameter, its receiver and its return. Every one the caller's text,
        // character for character. `receiverKdoc` was the route this assertion missed; it was
        // exercised only by "it compiles", which would not notice a `%S` silently eating an
        // argument.
        assertEquals(7, rendered.windowed(text.length).count { it == text })
    }

    @Test
    fun `a file comment is the generated-do-not-edit banner`() {
        assertEquals(
            """
            // Generated by poetdsl. Do not edit.
            package com.example


            """.trimIndent(),
            file("com.example", "A", fileComment = "Generated by poetdsl. Do not edit.") { }.toString(),
        )
    }

    @Test
    fun `every declaration construct takes kdoc`() {
        assertEquals(
            """
            package com.example

            import kotlin.Int

            /**
             * A documented property.
             */
            public val top: Int = 1

            /**
             * A documented function.
             */
            public fun f() {
            }

            /**
             * A documented class.
             *
             * @param id the identifier
             */
            public class C(
              /**
               * the identifier
               */
              public val id: Int,
            ) {
              /**
               * A documented member.
               */
              public var m: Int = 0

              /**
               * A documented secondary constructor.
               */
              public constructor(other: Int) : this(other)
            }

            /**
             * A documented interface.
             */
            public interface I

            /**
             * A documented object.
             */
            public object O

            """.trimIndent(),
            file("com.example", "A") {
                `val`("top", INT, init = 1.lit, kdoc = "A documented property.")
                `fun`("f", kdoc = "A documented function.") { }
                `class`(
                    "C",
                    param(VAL, "id", INT, kdoc = "the identifier"),
                    kdoc = "A documented class.",
                ) { _ ->
                    `var`("m", INT, init = 0.lit, kdoc = "A documented member.")
                    `constructor`(param("other", INT), kdoc = "A documented secondary constructor.") { o ->
                        `this`(o)
                    }
                }
                `interface`("I", kdoc = "A documented interface.") { }
                `object`("O", kdoc = "A documented object.") { }
            }.toString(),
        )
    }

    @Test
    fun `a fun documents its receiver, its parameters and its return`() {
        assertEquals(
            """
            package com.example

            import kotlin.Int
            import kotlin.String

            /**
             * Repeats this string.
             *
             * @receiver the string to repeat
             * @param n how many times
             * @return the repeated string
             */
            public fun String.repeated(n: Int): String = this.repeat(n)

            """.trimIndent(),
            file("com.example", "A") {
                `fun`(
                    "repeated",
                    param("n", INT, kdoc = "how many times"),
                    returns = STRING,
                    receiver = STRING,
                    kdoc = "Repeats this string.",
                    receiverKdoc = "the string to repeat",
                    returnsKdoc = "the repeated string",
                ) { n -> ret(expression("this").call("repeat", n)) }
            }.toString(),
        )
    }

    @Test
    fun `the in-body constructorParam takes kdoc too`() {
        assertEquals(
            """
            package com.example

            import kotlin.Int

            /**
             * @param id the identifier
             */
            public class C(
              /**
               * the identifier
               */
              public val id: Int,
            )

            """.trimIndent(),
            file("com.example", "A") {
                `class`("C") { constructorParam(VAL, "id", INT, kdoc = "the identifier") }
            }.toString(),
        )
    }

    @Test
    fun `the detached builders take kdoc`() {
        assertEquals(
            """
            package com.example

            import kotlin.Int

            /**
             * A detached type.
             */
            public class T

            /**
             * A detached function.
             *
             * @return nothing useful
             */
            public fun g(): Int = 1

            /**
             * A detached property.
             */
            public val p: Int = 1

            """.trimIndent(),
            file("com.example", "A") {
                +typeSpec(name = "T", kdoc = "A detached type.") { }
                +funSpec(
                    name = "g",
                    returns = INT,
                    kdoc = "A detached function.",
                    returnsKdoc = "nothing useful",
                ) { ret(1.lit) }
                +propertySpec(name = "p", type = INT, init = 1.lit, kdoc = "A detached property.")
            }.toString(),
        )
    }

    /**
     * The named and the anonymous overload put `name: String` and `kdoc: String? = null` in the same
     * position, which is the one shape that can rebind *silently* rather than failing at the
     * caller's compile. It does not: Kotlin picks the more specific `String`. Measured at base and
     * at head — see D35 — and pinned here so a later reordering cannot quietly change it.
     */
    @Test
    fun `a companion object takes kdoc, and naming one still names it`() {
        assertEquals(
            """
            package com.example

            public class C {
              /**
               * The factory.
               */
              public companion object Factory
            }

            public class D {
              /**
               * The anonymous one.
               */
              public companion object
            }

            """.trimIndent(),
            file("com.example", "A") {
                `class`("C") { companionObject("Factory", kdoc = "The factory.") { } }
                `class`("D") { companionObject(kdoc = "The anonymous one.") { } }
            }.toString(),
        )
    }

    /**
     * The fourth place a caller's documentation would be dropped on the floor, after `receiverKdoc`
     * with no receiver, `returnsKdoc` on a `Unit` function and a local binding's `kdoc`.
     *
     * KotlinPoet 2.3.0's `TypeSpec.emit` walks its `funSpecs` twice and calls
     * `FunSpec.emit(…, includeKdocTags)` with **`false` for every `isConstructor` spec and `true`
     * for every other one** (read off the bytecode: `iconst_0` on the constructor branch,
     * `iconst_1` on the function branch). With the flag false, `FunSpec.emit` writes `kdoc` alone
     * instead of `kdocWithTags()`, and `@param` lives only in the latter. So
     * `` `constructor`(param("s", INT, kdoc = "the doc")) `` rendered `public constructor(s: Int)`
     * and the text existed nowhere — while the identical parameter on a member `` `fun` ``, on a
     * top-level one, on `funSpec`, and on the *primary* constructor (whose tags KotlinPoet folds
     * into the class's own KDoc) all render it. A standalone `FunSpec.toString()` renders it too,
     * which is what makes this specific to the member position.
     */
    @Test
    fun `a secondary constructor's parameter cannot carry kdoc`() {
        val e = assertFailsWith<IllegalStateException> {
            file("com.example", "A") {
                `class`("C") { `constructor`(param("s", INT, kdoc = "the doc")) { _ -> } }
            }
        }
        assertEquals(
            "param: \"s\" carries kdoc and this is a secondary constructor, where KotlinPoet emits " +
                "the constructor's own kdoc without the `@param` tags — so the text would reach no " +
                "output at all. Write it into the constructor's kdoc as an `@param s …` line, or " +
                "drop it.",
            e.message,
        )
    }

    /** The remedy the message names, rendered. */
    @Test
    fun `a secondary constructor documents its parameters in its own kdoc`() {
        assertEquals(
            """
            package com.example

            import kotlin.Int

            public class C {
              /**
               * Builds one.
               *
               * @param s the doc
               */
              public constructor(s: Int)
            }

            """.trimIndent(),
            file("com.example", "A") {
                `class`("C") {
                    `constructor`(param("s", INT), kdoc = "Builds one.\n\n@param s the doc") { _ -> }
                }
            }.toString(),
        )
    }

    @Test
    fun `a receiver kdoc with no receiver is rejected`() {
        val e = assertFailsWith<IllegalStateException> {
            file("com.example", "A") { `fun`("f", receiverKdoc = "the receiver") { } }
        }
        assertEquals(
            "`fun`: 'f' documents a receiver with receiverKdoc but declares none. Pass receiver = …, " +
                "or move the text into kdoc.",
            e.message,
        )
    }

    @Test
    fun `a return kdoc on a Unit function is rejected`() {
        val e = assertFailsWith<IllegalStateException> {
            file("com.example", "A") { `fun`("f", returnsKdoc = "the answer") { } }
        }
        assertEquals(
            "`fun`: 'f' documents a return value with returnsKdoc but returns Unit. Pass returns = …, " +
                "or move the text into kdoc.",
            e.message,
        )
    }

    @Test
    fun `a local binding cannot carry kdoc`() {
        val e = assertFailsWith<IllegalStateException> {
            file("com.example", "A") { `fun`("f") { `val`("x", INT, init = 1.lit, kdoc = "nope") } }
        }
        assertEquals("A local binding ('x') cannot carry KDoc; only a declaration can.", e.message)
    }

    /**
     * A `%` reaching KotlinPoet unescaped is not always loud: `%S` with an argument available
     * silently consumes it. This pins the *loud* half — the shape a caller is most likely to write
     * — as a fact about KotlinPoet rather than about this DSL, so that the day `addKdoc` stops
     * throwing, the reason `"%L"` is used everywhere is still on the record.
     */
    @Test
    fun `KotlinPoet's own addKdoc still treats its argument as a format string`() {
        val e = kotlin.runCatching {
            com.squareup.kotlinpoet.FunSpec.builder("f").addKdoc("100% done").build()
        }.exceptionOrNull()
        assertTrue(e is IllegalArgumentException, "expected IllegalArgumentException, got $e")
        assertEquals("index 1 for '% ' not in range (received 0 arguments)", e.message)
    }
}
